# -*- coding: utf-8 -*-
"""Python modules.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WDeqkXYA47B096Tno2HD-ZLA42MSEFKq
"""

import json

jsonData = '{"name": "Opeyemi", "age": 20, "address": "Anything anything", "phoneNumber": "+12878472384"}'

newData = json.loads(jsonData)

newData['name']

decoded_data = json.dumps(newData)

decoded_data

import requests

api = 'https://randomuser.me/api/'
response = requests.get(api)
if response.status_code==200:
  data = response.json()
else:
  print('Something went wrong')

data['results'][0]

data['results'][0]['gender']

name = data['results'][0]['name']
name

name['first']

location = data['results'][0]['location']
location

streetInfo = location['street']
streetInfo

streetInfo['name']

picture = data['results'][0]['picture']['large']
picture

# pip install pillow

from PIL import Image
from io import BytesIO
from IPython.display import display

getImage = requests.get('https://randomuser.me/api/portraits/women/32.jpg')
getImage

image = Image.open(BytesIO(getImage.content))

display(image)

# 1. Write a program that asks the user for their name and then prints a greeting using their name. For example: Hello, Tobi. How are you doing today.
name = input('Enter your name')
print(f'Hello {name}, good day.')

yourYearofAge = int(input('Enter your year: '))
age = 2023 - yourYearofAge
print(f'Your age is {age}')

color = input('enter your favorite color:')
print(f'Your color is {color}')